[build]
target = "thumbv7em-none-eabi"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# This runner will make a UF2 file and then copy it to a mounted mcu in USB
# Bootloader mode:
runner = "elf2uf2-rs -d"
# runner = "probe-rs run --chip nRF52840_xxAA --speed 20000"

[env]
DEFMT_LOG = "info"
